---
driver:
  name: vagrant
  config:
    require_chef_omnibus: true
  customize:
    memory: 1024
    cpus: 1
  network:

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: kitchen

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[collectd-ng::default]
    attributes:
      collectd-ng:
        plugins: []
  - name: package
    run_list:
      - recipe[collectd-ng::default]
    attributes:
      collectd-ng:
        install_method: 'package'
        plugins: []
