name             'collectd-ng'
maintainer       'E Camden Fisher'
maintainer_email 'camden@northpage.com'
license          'Apache 2.0'
description      'Installs/Configures collectd'
long_description 'Installs/Configures collectd'
version          '0.1.0'

depends 'yum', '~> 3.4.1'
depends 'yum-epel', '~> 0.5.2'
depends 'build-essential', '~> 2.1.3'
